from __future__ import annotations

_TRANSITIONS: dict[str, set[str]] = {
    "INBOX_NEW": {"INBOX_QUEUED", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "INBOX_QUEUED": {"PROCESSING_LOCKED", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "PROCESSING_LOCKED": {"ANALYSIS_RUNNING", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "ANALYSIS_RUNNING": {
        "DUPLICATE_CANDIDATE",
        "CLASSIFICATION_READY",
        "ERROR_RETRYABLE",
        "ERROR_BLOCKING",
    },
    "DUPLICATE_CANDIDATE": {"INBOX_TRASH_PENDING_MANUAL", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "CLASSIFICATION_READY": {"ROUTE_PROPOSED", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "ROUTE_PROPOSED": {
        "TAXONOMY_UPDATE_REQUIRED",
        "ROUTE_CONFIRMED",
        "USER_CONFIRMATION_REQUIRED",
        "ERROR_RETRYABLE",
        "ERROR_BLOCKING",
    },
    "TAXONOMY_UPDATE_REQUIRED": {"USER_CONFIRMATION_REQUIRED", "ROUTE_CONFIRMED", "ERROR_BLOCKING"},
    "USER_CONFIRMATION_REQUIRED": {"ROUTE_CONFIRMED", "ERROR_BLOCKING"},
    "ROUTE_CONFIRMED": {"LIBRARY_STORED", "ERROR_RETRYABLE", "ERROR_BLOCKING"},
    "INBOX_TRASH_PENDING_MANUAL": {"ERROR_BLOCKING"},
}


def can_transition(current_state: str, next_state: str) -> bool:
    return next_state in _TRANSITIONS.get(current_state, set())
